// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LoadDwhVenta.DatabaseObjects.Context.Configurations;
using LoadDwhVenta.DatabaseObjects.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace LoadDwhVenta.DatabaseObjects.Context;

public partial class NorthwindContext : DbContext
{
    public NorthwindContext()
    {
    }

    public NorthwindContext(DbContextOptions<NorthwindContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DimCategory> DimCategories { get; set; }

    public virtual DbSet<DimCustomer> DimCustomers { get; set; }

    public virtual DbSet<DimDate> DimDates { get; set; }

    public virtual DbSet<DimEmployee> DimEmployees { get; set; }

    public virtual DbSet<DimProduct> DimProducts { get; set; }

    public virtual DbSet<DimShipper> DimShippers { get; set; }

    public virtual DbSet<FactClientesAtendido> FactClientesAtendidos { get; set; }

    public virtual DbSet<FactOrder> FactOrders { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=Anthony0420;Initial Catalog=dwventas;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.DimCategoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DimCustomerConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DimDateConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DimEmployeeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DimProductConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DimShipperConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FactClientesAtendidoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FactOrderConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
