// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LoadDwhVenta.DatabaseObjects.Context;
using LoadDwhVenta.DatabaseObjects.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.DatabaseObjects.Context.Configurations
{
    public partial class DimCategoryConfiguration : IEntityTypeConfiguration<DimCategory>
    {
        public void Configure(EntityTypeBuilder<DimCategory> entity)
        {
            entity.HasKey(e => e.CategoryKey);

            entity.ToTable("DimCategory");

            entity.Property(e => e.CategoryKey).ValueGeneratedNever();
            entity.Property(e => e.CategoryName).HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DimCategory> entity);
    }
}
