// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LoadDwhVenta.DatabaseObjects.Context;
using LoadDwhVenta.DatabaseObjects.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.DatabaseObjects.Context.Configurations
{
    public partial class DimDateConfiguration : IEntityTypeConfiguration<DimDate>
    {
        public void Configure(EntityTypeBuilder<DimDate> entity)
        {
            entity.HasKey(e => e.DateKey).HasName("PK__DimDate__40DF45E3045E0EE9");

            entity.ToTable("DimDate");

            entity.Property(e => e.DateKey).ValueGeneratedNever();
            entity.Property(e => e.DateName).HasMaxLength(50);
            entity.Property(e => e.MonthName).HasMaxLength(50);
            entity.Property(e => e.YearName).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DimDate> entity);
    }
}
