// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LoadDwhVenta.DatabaseObjects.Context;
using LoadDwhVenta.DatabaseObjects.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.DatabaseObjects.Context.Configurations
{
    public partial class DimEmployeeConfiguration : IEntityTypeConfiguration<DimEmployee>
    {
        public void Configure(EntityTypeBuilder<DimEmployee> entity)
        {
            entity.HasKey(e => e.EmployeeKey).HasName("PK__DimEmplo__8749E50A368F0127");

            entity.ToTable("DimEmployee");

            entity.Property(e => e.EmployeeName)
                .HasMaxLength(100)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DimEmployee> entity);
    }
}
