// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LoadDwhVenta.DatabaseObjects.Context;
using LoadDwhVenta.DatabaseObjects.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.DatabaseObjects.Context.Configurations
{
    public partial class FactOrderConfiguration : IEntityTypeConfiguration<FactOrder>
    {
        public void Configure(EntityTypeBuilder<FactOrder> entity)
        {
            entity.HasKey(e => e.OrderNumber).HasName("PK__FactOrde__CAC5E742F4A7BA50");

            entity.Property(e => e.OrderNumber).ValueGeneratedNever();
            entity.Property(e => e.City)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TotalVentas).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.CustomerKeyNavigation).WithMany(p => p.FactOrders)
                .HasForeignKey(d => d.CustomerKey)
                .HasConstraintName("FK__FactOrder__Custo__59063A47");

            entity.HasOne(d => d.EmployeeKeyNavigation).WithMany(p => p.FactOrders)
                .HasForeignKey(d => d.EmployeeKey)
                .HasConstraintName("FK__FactOrder__Emplo__571DF1D5");

            entity.HasOne(d => d.ProductKeyNavigation).WithMany(p => p.FactOrders)
                .HasForeignKey(d => d.ProductKey)
                .HasConstraintName("FK__FactOrder__Produ__5629CD9C");

            entity.HasOne(d => d.ShipperKeyNavigation).WithMany(p => p.FactOrders)
                .HasForeignKey(d => d.ShipperKey)
                .HasConstraintName("FK__FactOrder__Shipp__5812160E");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FactOrder> entity);
    }
}
