// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LoadDwhVenta.DatabaseObjects.Context;
using LoadDwhVenta.DatabaseObjects.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.DatabaseObjects.Context.Configurations
{
    public partial class FactClientesAtendidoConfiguration : IEntityTypeConfiguration<FactClientesAtendido>
    {
        public void Configure(EntityTypeBuilder<FactClientesAtendido> entity)
        {
            entity.HasKey(e => e.ClienteAtendidoKey).HasName("PK__FactClie__B70C6B93F884893C");

            entity.HasOne(d => d.EmployeeKeyNavigation).WithMany(p => p.FactClientesAtendidos)
                .HasForeignKey(d => d.EmployeeKey)
                .HasConstraintName("FK__FactClien__Emplo__534D60F1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FactClientesAtendido> entity);
    }
}
