// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.DatabaseObjects.Models;

public partial class NumeroPedidosPorEmpleado
{
    public int EmployeeId { get; set; }

    public string NombreEmpleado { get; set; }

    public int? NumeroPedidos { get; set; }
}