// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.DatabaseObjects.Models;

public partial class NumeroOrdenesPorCliente
{
    public string CustomerId { get; set; }

    public string Cliente { get; set; }

    public int? NumeroOrdenes { get; set; }
}