// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.DatabaseObjects.Models;

public partial class ProductosMasVendidosPorCategorium
{
    public string Categoria { get; set; }

    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int? CantidadVendida { get; set; }
}