// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.DatabaseObjects.Models;

public partial class VentasPorCategorium
{
    public string Categoria { get; set; }

    public decimal? VentasTotales { get; set; }
}