// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.DatabaseObjects.Models;

public partial class ViewProducto
{
    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public short? Inventario { get; set; }

    public decimal? PreciVenta { get; set; }

    public decimal? Costo { get; set; }
}