// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.DatabaseObjects.Entities;

public partial class DimCustomer
{
    public int CustomerKey { get; set; }

    public string CustomerName { get; set; }

    public virtual ICollection<FactOrder> FactOrders { get; set; } = new List<FactOrder>();
}