// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.DatabaseObjects.Entities;

public partial class DimEmployee
{
    public int EmployeeKey { get; set; }

    public string EmployeeName { get; set; }

    public virtual ICollection<FactClientesAtendido> FactClientesAtendidos { get; set; } = new List<FactClientesAtendido>();

    public virtual ICollection<FactOrder> FactOrders { get; set; } = new List<FactOrder>();
}