// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.Models.Models;

public partial class FactClientesAtendido
{
    public int ClienteAtendidoKey { get; set; }

    public int EmployeeKey { get; set; }

    public int TotalClientes { get; set; }
}