// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwhVenta.Models.Models;

public partial class FactOrder
{
    public int OrderNumber { get; set; }

    public int ProductKey { get; set; }

    public int EmployeeKey { get; set; }

    public int Shipper { get; set; }

    public int CustomerKey { get; set; }

    public string Country { get; set; }

    public decimal TotalVentas { get; set; }

    public int CantidadVentas { get; set; }

    public int CategoryKey { get; set; }
}